### ISSUE TITLE
openssl issue

### ISSUE THREAD

**Issue by cis-sabahat** [bitcoinplusorg/xbcwalletsource#3]
When I try to compile the code on ubuntu with latest openssl version it gives me following error:

tor/aes.c:93:18: error: field ‘evp’ has incomplete type
   EVP_CIPHER_CTX evp;
                  ^
makefile.unix:285: recipe for target 'obj/aes.o' failed
make: *** [obj/aes.o] Error 1

But same thing works properly with openssl version 1.0.1f

I have  to make it work with latest version

**Comment by Bushstar** [comment]
Which branch are you compiling?

origin is currently the safe branch, master-pre0.9 is work in progress and not all additional features are fully working.

**Comment by cis-sabahat** [comment]
@Bushstar I am compiling origin branch

**Comment by Bushstar** [comment]
Do you have libevent installed?

sudo apt-get install libevent-dev

**Comment by cis-sabahat** [comment]
Yes its installed.

**Comment by Bushstar** [comment]
Looks a lot like the errors you get when the libevent is not found. Just built on Ubuntu 16.04 to test, checking my libevent packages I have the following. Please make sure you have these packages. Let me know what Ubuntu version you are running.

```
apt list --installed | grep event

libevent-2.0-5/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed,automatic]
libevent-core-2.0-5/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed,automatic]
libevent-dev/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed]
libevent-extra-2.0-5/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed,automatic]
libevent-openssl-2.0-5/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed,automatic]
libevent-pthreads-2.0-5/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed,automatic]
```

**Comment by cis-sabahat** [comment]
Yes I have the following packeges installed on my system

libevent-2.0-5/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed]
libevent-core-2.0-5/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed]
libevent-dev/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed]
libevent-extra-2.0-5/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed,automatic]
libevent-openssl-2.0-5/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed,automatic]
libevent-pthreads-2.0-5/xenial-updates,xenial-security,now 2.0.21-stable-2ubuntu0.16.04.1 amd64 [installed,automatic]
libtevent0/xenial-updates,xenial-security,now 0.9.28-0ubuntu0.16.04.1 amd64 [installed,automatic]

**Comment by Bushstar** [comment]
It should compile if you use OpenSSL 1.0.2g, if you are trying to compile with 1.1 you will not get past the error. This problem will be rectified only when the integrate Tor client is updated.

```
libssl1.0.0/xenial-updates,now 1.0.2g-1ubuntu4.8 amd64 [installed]
openssl/xenial-updates,now 1.0.2g-1ubuntu4.8 amd64 [installed,automatic]
```

**Comment by cis-sabahat** [comment]
I have used 1.0.2g. Please have  a look over screen shot
![screenshot from 2017-09-30 16-56-52](https://user-images.githubusercontent.com/16253009/31045409-a998ee58-a600-11e7-8c5d-8e07661d9082.png)

**Comment by Bushstar** [comment]
It is a documented issue with OpenSSL 1.1. If you've been trying different version then please run:

make -f makefile.unix clean

The issue is reported here:

https://oniongit.eu/asn/tor/commit/2a365413ebc7ab0055bd4c2fc11697666fc90f7b

There is a patch for it here you may want to try:

https://oniongit.eu/asn/tor/commit/2a365413ebc7ab0055bd4c2fc11697666fc90f7b

**Comment by cis-sabahat** [comment]
I have tried your solution and now the evp error has gone but when I compile the code it is giving me this error:

In file included from tor/aes.c:55:0:
/home/cis/Projects/xbcwalletsource/src/compat.h:50:32: error: expected ‘;’, ‘,’ or ‘)’ before ‘&’ token
 inline int myclosesocket(SOCKET& hSocket)
                                ^
In file included from /home/cis/Projects/xbcwalletsource/src/util.h:9:0,
                 from tor/aes.c:57:
/home/cis/Projects/xbcwalletsource/src/uint256.h:9:18: fatal error: string: No such file or directory
compilation terminated.

this uint256.h file is present in src but giving error

![screenshot from 2017-10-03 12-43-13](https://user-images.githubusercontent.com/16253009/31113839-e3d577be-a838-11e7-8c53-12037dc1a020.png)

**Comment by Bushstar** [comment]
It can find uint256.h but is complaining about the line...

`#include <string>`

You said that it works 1.0.1.

> But same thing works properly with openssl version 1.0.1f

Compilation should also work with OpenSSL 1.0.2. Once the basic 0.9 client is working I'll look at updating the Tor client and test compatibility with newer versions of OpenSSL.

**Comment by cis-sabahat** [comment]
Yes it is working for 1.0.1f
